- name: "Setup server"
  hosts: web
  vars_files:
    - vars/main.yml
  tasks:
    - include_tasks: tasks/env-setup.yml
    - include_tasks: tasks/install-nginx.yml
    - include_tasks: tasks/install-docker.yml
    - include_tasks: tasks/install-go.yml
    - include_tasks: tasks/install-nodejs.yml
    - include_tasks: tasks/install-flyway.yml