- name: "Get node setup file"
  ansible.builtin.shell:
    cmd: "curl https://deb.nodesource.com/setup_{{node_version}}.x | sudo -E bash -"
  args:
    executable: /bin/bash
  become: yes

- name: "Install nodejs"
  ansible.builtin.package:
    name: nodejs
    state: present
  become: yes